### ISSUE TITLE
Handling of Unicode escape looks odd

### ISSUE THREAD

**Issue by eed3si9n** [scalacenter/scalafix#619]
This is not directly related to ProcedureSyntax, but I noticed it when I ran it against scala/scala.

### steps

Run ProcedureSyntax to

```scala
def a = (1, 2, 3) match { case (r, \u03b8, \u03c6) => r + \u03b8 + \u03c6 }
```

### problem

From https://gist.github.com/olafurpg/94d77311532cc538cc1f1241df8f5901

```diff
diff --git a/test/files/run/t3835.scala b/test/files/run/t3835.scala
index 186ee36dca..713e8bf62e 100644
--- a/test/files/run/t3835.scala
+++ b/test/files/run/t3835.scala
@@ -2,8 +2,8 @@ object Test extends App {
   // work around optimizer bug scala/bug#5672  -- generates wrong bytecode for switches in arguments
   // virtpatmat happily emits a switch for a one-case switch
   // this is not the focus of this test, hence the temporary workaround
-  def a = (1, 2, 3) match { case (r, \u03b8, \u03c6) => r + \u03b8 + \u03c6 }
+  def a = (1, 2, 3) match { case (r, 8, 6) => r + 8 + 6 }
   println(a)
-  def b = (1 match { case \u00e9 => \u00e9 })
+  def b = (1 match { case 9 => 9 })
   println(b)
 }
```

### expectation

No changes.
This one is scary because I think it would still compile.

**Comment by olafurpg** [comment]
Thanks for reporting! This is fixed in https://github.com/scalameta/scalameta/pull/1270 and an upgrade is in https://github.com/scalacenter/scalafix/pull/615

I agree this is scary, scalafmt has the same bug but unfortunately it's not so easy to upgrade to the latest scalameta to enjoy the fix https://github.com/scalameta/scalafmt/issues/1110

**Comment by olafurpg** [comment]
I am able to reproduce with the latest version despite the fix in https://github.com/scalameta/scalameta/pull/1270 Seems unicode literals in pattern position are still problematic. I've reported this upstream in scalameta with a minimal reproduction. Superseded by https://github.com/scalameta/scalameta/issues/1574

**Comment by eed3si9n** [comment]
Since the end user would still experience this issue, what do you think about keeping this open until the fixed upstream is merged into Scalafix? sbt uses a label to track these - https://github.com/sbt/sbt/labels/Blocked%20on%20Upstream

**Comment by olafurpg** [comment]
For better or worse, I personally try to limit the issue tracker to actionable items that can be fixed in this repo. By having tickets open in multiple repos for the same bug you risk fixing the issue in the upstream repo but forgetting to close affected tickets in downstream repos. Users who are interested in tracking the ticket should subscribe to the upstream Scalameta ticket.
